FROM python:3.6.13-buster

RUN apt update && apt install -y net-tools iputils-ping vim tcpdump

WORKDIR /app
COPY ./upnpy_auth ./upnpy_auth
COPY ./demo.py .
COPY ./client.py ./auth_client.py ./requirements.txt ./

RUN python3 -m pip install -r requirements.txt

COPY ./user_password.txt ./rs256.key ./rs256.key.pub ./cert.pem ./

#default settings
ENV auth_server_addr="172.16.0.150:50000"

CMD /bin/bash